CREATE DATABASE IF NOT EXISTS smart_home;

USE smart_home;

CREATE TABLE IF NOT EXISTS devices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'off'
);

ALTER TABLE devices ADD COLUMN type VARCHAR(255) NOT NULL;

CREATE DATABASE IF NOT EXISTS smart_home;

USE smart_home;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);